AllCops:
  TargetRubyVersion: 2.4

Rails:
  Enabled: true

Style/ClassAndModuleChildren:
  Exclude:
    - "**/*.rb"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
